// Code generated by avro/gen. DO NOT EDIT.
package testpkg

import (
	"fmt"
	"strings"
)

// ClickEvent is a generated struct.
type ClickEvent struct {
	URL string `avro:"url"`
}

// PurchaseEvent is a generated struct.
type PurchaseEvent struct {
	Amount int64 `avro:"amount"`
}

// Event is a generated struct.
type Event struct {
	Payload *EventPayloadUnion `avro:"payload"`
}

// EventPayloadUnion is a generated union wrapper.
type EventPayloadUnion struct {
	ClickEvent    *ClickEvent
	PurchaseEvent *PurchaseEvent
}

func (u *EventPayloadUnion) validate() error {
	var set []string
	if u.ClickEvent != nil {
		set = append(set, "ClickEvent")
	}
	if u.PurchaseEvent != nil {
		set = append(set, "PurchaseEvent")
	}
	if len(set) > 1 {
		return fmt.Errorf("EventPayloadUnion: multiple fields set: %s", strings.Join(set, ", "))
	}
	return nil
}

func (u *EventPayloadUnion) ToAny() (any, error) {
	if err := u.validate(); err != nil {
		return nil, err
	}
	if u.ClickEvent != nil {
		return u.ClickEvent, nil
	}
	if u.PurchaseEvent != nil {
		return u.PurchaseEvent, nil
	}
	return nil, fmt.Errorf("no value set in EventPayloadUnion")
}

func (u *EventPayloadUnion) FromAny(payload any) error {
	switch t := payload.(type) {
	case ClickEvent:
		u.ClickEvent = &t
	case PurchaseEvent:
		u.PurchaseEvent = &t
	default:
		return fmt.Errorf("unknown type %T in EventPayloadUnion", payload)
	}
	return nil
}
